language: ruby
cache: bundler
rvm:
- 2.3.0
sudo: false
deploy:
  provider: chef-supermarket
  user_id: annih
  client_key: .travis/annih.pem
  cookbook_category: Other
  skip_cleanup: true
  on:
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_56687d638eba_key -iv $encrypted_56687d638eba_iv -in .travis/annih.pem.enc -out .travis/annih.pem -d
